### ISSUE TITLE
Filtering for transactions

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#11]
I want to be able to filter transactions in my account view to see specific ones.

For example, if I type "landlord", I want to see all the transactions where: recipient is "landlord".

**Comment by bpaulien** [comment]
include notes and category in the search.  if not everything at once, at least a toggle to determine which to include.  Also ability to include search for amounts.

**Comment by bpaulien** [comment]
filters also to show or hide uncleared/cleared/verified transactions as desired.

**Comment by justbudget** [comment]
Note, these filters should persist, per the request here: https://github.com/justbudget/justbudget/issues/43

**Comment by justbudget** [comment]
This is done as of: https://www.reddit.com/r/justbudget/comments/xkzz1o/update_64_search_filter_transactions/?utm_source=share&utm_medium=web2x&context=3 (except for the "persisting" logic)
