### ISSUE TITLE
Sort transactions by date, then by date/time added

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#14]
Use case:

If I have 3 transactions in my credit card on 07/08/22, I want to add them in the order they appear on my credit card statement. Then, I want them to stay in that order when I'm sorting by "date" in the accounts view. This will make it easier to compare JustBudget to my credit card.

**Comment by blounsbury-usbr** [comment]
Just a note that the new inline transactions behave almost like this. Transactions with the same data are saved to the top of the list as they are added until the final transaction is entered and you hit 'Cancel' to stop adding transactions. The last transaction entered then goes to the bottom of the list of transactions with the same date instead of the top like the other transactions just entered. So, if that final transaction would stay on top, this issue would be fixed, at least for inline transactions.

**Comment by blounsbury** [comment]
I'd love to see this get pushed to p1. It really is difficult to compare budget transactions to account transactions when they are out of order from when I entered them in the budget.

**Comment by justbudget** [comment]
OK, thanks for letting me know. I've bumped this up from a P2 to a P1!

**Comment by justbudget** [comment]
This should be done now. Changes are live on the website. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/106850056/187441531-475cafa3-e80e-4fce-ac49-9a222df1bf8c.gif)

**Comment by blounsbury** [comment]
Fantastic!!

**Comment by Kidglove57** [comment]
Great progress yet again - thank you!! Whilst this does not impact me directly (as I would never remember to enter my transactions in the exact time order they were incurred!) it is  nonetheless another move towards greater usability - thank you.

**Comment by blounsbury** [comment]
Hmm ... yesterday I entered a transaction for 9/1/22. Today I entered two more for 9/1/22 and today's transactions dropped down below yesterday's.

![image](https://user-images.githubusercontent.com/109162006/188181716-900b1670-a6a8-40d4-b5ef-fde4313eda64.png)

**Comment by justbudget** [comment]
Thanks for catching this @blounsbury ! The screenshot helped show the issue - transfers weren't being sorted properly. Applied a fix and should be working now

**Comment by blounsbury** [comment]
Sweet! Thank you! It seems like such a small thing, but it really does make it so so much easier to check against my bank or credit card line by line and compare or pick up where I left off and add new transactions. Thanks again!
