### ISSUE TITLE
In-line adding of transactions

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#39]
I want to be able to add a transaction in row form, filling out the fields in the table, similar to editing an existing one.

**Comment by bpaulien** [comment]
QOL note regarding this issue...  Please keep the same date as the previous entry by default.  

Let's say I have 5 new transactions to enter.  I have 3 transactions on the 8th, and 2 on the 9th...

I click add, and a new blank line appears at the top of the register.  I select (either from date selector, or  by hitting shift-arrow) the correct date (8th).  Then I hit tab, and enter the rest of the information, and hit Enter.  That transaction is saved, and another blank entry appears at the top of the register.  The date is the 8th by default, so I don't have to change anything.  I enter the next 2 records.  Now after the 3rd entry, I hit enter, and the date is still 8th.  I'm ready to start entering records from the 9th, so I select that date, and enter the next 2 records.

**Comment by justbudget** [comment]
Done: 
https://www.reddit.com/r/justbudget/comments/vb0s7z/update_48_add_new_transactions_inline/

> Please keep the same date as the previous entry by default.

Done!
