### ISSUE TITLE
Display Selected Totals

### ISSUE THREAD

**Issue by InsouciantQualms** [justbudget/justbudget#44]
Use Case:

I would like to select one or more transactions (likely via checkboxes) and have the UI show what the subtotal of just those transactions adds up to.

**Comment by justbudget** [comment]
This is fixed as of: https://www.reddit.com/r/justbudget/comments/xlgrsk/update_65_view_subtotals_of_selected_transactions/?utm_source=share&utm_medium=web2x&context=3
