### ISSUE TITLE
Should be able to add income in-line

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#53]
Right now when adding transactions in-line, you can only enter expenses, regardless of whether you make it a positive or negative value.

I think it should be that if you put a `+`, it will be treated as income.

**Comment by justbudget** [comment]
This is now fixed, the behavior is:

* `100` is a $100 expense
* `-100` is a $100 expense
* `+100` is a $100 income

![giphy-1](https://user-images.githubusercontent.com/106850056/184500299-988f94a9-64b6-423d-a22a-6d8ff329a9ca.gif)

**Comment by Rick-Thomas** [comment]
It's not working on my laptop...   

I wonder if it's a windows configuration problem???   

I'm on W11, don't have a numeric keypad, and the keyboard setup is Spanish LatinAmerica (Argentina)...   Not sure if this is not part of the date format (DD/MM/YYYY) issue that was brought up some time ago...

**Comment by justbudget** [comment]
No, I don't believe it would be a configuration problem. My suspicion is that you still have an older version of the app in your browser. I think refreshing the page and trying again would do it. If that doesn't work I would try clearing cache and reloading. Hope it works for you!

**Comment by Rick-Thomas** [comment]
Just tried again and it worked great!!!   Thanks...
