### ISSUE TITLE
Can't type 'q' or 'Q' using inline transactions

### ISSUE THREAD

**Issue by blounsbury-usbr** [justbudget/justbudget#67]
Prior to inline transactions, typing 'q' would pop-up the add transaction dialog. Now I am unable to type 'q' or 'Q' in any of the inline input boxes. When I type 'q' the add transaction dialog pops-up rather than allowing me to type 'q' in, for example, the Recipient box of the inline transaction.

**Comment by justbudget** [comment]
Ah good catch! I disabled the `q` keyboard shortcut when an inline transaction is in progress.

Should be fixed on the web version now.
