### ISSUE TITLE
Entering Transaction Error

### ISSUE THREAD

**Issue by Rick-Thomas** [justbudget/justbudget#68]
When entering an new in-line transaction, if I press Shift-Q in the Recipient field it opens the Add Transaction window...   I entered the whole alphabet pressing Shift-letter, but the Q was the only one to react this way...

**Comment by justbudget** [comment]
Thanks for filing this, another user was having this experience too: https://github.com/justbudget/justbudget/issues/67

It should be fixed now!

**Comment by Rick-Thomas** [comment]
Great!!!   Tks for the quick response...
