### ISSUE TITLE
Inline Transaction Bug

### ISSUE THREAD

**Issue by Rick-Thomas** [justbudget/justbudget#70]
When I input an Inline Transaction and type an invalid Category it defaults to "Available to Budget"...    

When I enter the transaction into the register two things happen:

1. The transaction has a blank Category...
2. This generates a situation in the Budget where I have a negative Available to Budget, which, if I didn't realize I made the error, and all my budget balances are green, is a complicated error to figure out and find!!!

I feel that there should be a warning in both the  Account and Balance highlighting there is a transaction with blank category and the account and transaction highlighted or marked to be able to locate and correct...

This situation happened to me just now, where I imputed 7 transactions corresponding to today's activity, in thee different accounts...   When I finished I noticed the red dot on the Budget icon, which surprised me because all expenses were within Budget...  I never noticed I misspelled a Category, which was replaced by Available to Budget!!!  All my budget balances were green, as expected, but I had a -$72 Available to Balance, which made no sense...   After a while I finally realized the blank category in one of the new transactions!!!   :-(

**Comment by justbudget** [comment]
Fixed! Thanks for filing this, see my comment here for the explanation for how the fix works: https://www.reddit.com/r/justbudget/comments/vnt7w9/comment/iei47z2/?utm_source=share&utm_medium=web2x&context=3
