### ISSUE TITLE
Budget doesn't update immediately after drag/drop deposit.

### ISSUE THREAD

**Issue by bpaulien** [justbudget/justbudget#73]
I tried leaving this on the reddit Beta Feedback post, but couldn't figure out how to include a screenshot. 

When I transfer money by drag/drop from one category to another, the "Budgeted" column doesn't update until you select a different category.  But the "Available" column does update.

Here's a shot right after dragging it, and selecting $210 to move into the category.
![image](https://user-images.githubusercontent.com/6487363/176963888-46c1ae35-0258-4e70-a79b-9c82dea84622.png)

as soon as I selected out of the category (Budgeted field was selected), it looked like this (as it should have initially)
![image](https://user-images.githubusercontent.com/6487363/176963990-860966e1-7728-4fe0-9306-6a29ce93e477.png)

**Comment by justbudget** [comment]
Thanks for filing this!

> When I transfer money by drag/drop from one category to another, the "Budgeted" column doesn't update until you select a different category. But the "Available" column does update.

Just to clarify I think the bug only happens when the current category is selected. 

In any case, I believe it's an easy fix. I tweaked the app and pushed a new version to the web. Should be live now!
