### ISSUE TITLE
Add a date picker to inline transaction adding.

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#79]
When entering a transaction inline, there should be a date-picker below the date field to easily select a date.

**Comment by bpaulien** [comment]
And in keeping with the goal of exclusive keyboard entry in the inline transaction input, make it so the date picker can respond to arrow keys, to easily move and select the needed date.  Even if it's only every so often that you'd need to change the date, moving off keyboard to the mouse is still a disruption of that flow.

**Comment by justbudget** [comment]
>  make it so the date picker can respond to arrow keys, to easily move and select the needed date.

I like this idea too but I worry that it would make it harder to edit the text directly. For example if I'm tweaking a date and it's `05/06/22|` (with my cursor at the end), and I want to move my cursor to the left, I would want to hit the arrow key. That would be impossible if the arrow key instead moves the date on the date selector. 

It might be a worthwhile trade-off but it's worth noting. It would just mean you have to either delete the whole date or click to the specific section you want to edit.

**Comment by bpaulien** [comment]
True, but I think once people realized that cursor keys moved the date rather than the cursor, they'd prefer it.  It would also save keystrokes, since you don't have to cursor over to the part of the date you want to change, then hit backspace or delete, and then type the number you wanted.  Just move to the date, and hit tab.

**Comment by Rick-Thomas** [comment]
And also consider the possibility of using the + and - keys to increase/decrease the day...

**Comment by bpaulien** [comment]
So, one more thought on using the arrow keys, and your concern that it would affect ability to change the text of the date.  In my mind, if the date picker is up, that's what you're using for selecting a date.  If you want to manually enter the text, hit escape or somehow close the date picker (Often if you click on the text part of the date, the picker will disappear, and you can enter with the keyboard) and enter the text using normal keyboard input.  Date pickers are meant to be an easier alternative to entering a date manually by the keyboard.

**Comment by Rick-Thomas** [comment]
To add to what @bpaulien says, the way YNAB4 handles the date field and the date picker is, when both are selected, the left/right arrows move in the date field and the up/down arrows move left/right in the date picker...    The Esc key leaves the date picker and goes back to the date field...   Can’t remember how nYNAB handles it…

I agree with the concept that when we are entering transactions, the less we have to jump from keyboard to mouse the better...  I'm a keyboard data entry guy!!!   :-)

**Comment by blounsbury** [comment]
Just chiming in to agree with @bpaulien. I think a date picker completely eliminates the need for manual entry and I would think in nearly any scenario is significantly faster than manual entry. 

Example, if in @justbudget's example with the cursor to the left of the year, 05/06/22|. To change that date to yesterday requires hitting the left arrow key 3 times, hitting the delete key, then typing 5 to change the date to 05/05/22, and then hit tab to the Recipient field. With a date picker you hit the left arrow key 1 time and hit tab to the Recipient field.

So:
manual entry = 6 keystrokes
date picker = 2 keystrokes

Voting for the date picker!

**Comment by justbudget** [comment]
Thanks for the feedback everyone! I think the best way forward is to add a date picker that responds to arrow key presses. Then, as a nice to have, when you click into the text field or hit `escape`, the date picker is dismissed and you can edit the text as normal.

Sounds like the date picker + arrow keys solves the majority of cases and would be valuable to have.

**Comment by justbudget** [comment]
This is now added as of: https://www.reddit.com/r/justbudget/comments/w5fmjb/update_52_date_picker_for_inline_transactions/

Should be live on the site now!

Currently the arrows are always +1 and -1 to the day (rather than moving the cursor), but that seems to be the most preferred behavior anyways. You can still click into the text field to move the cursor and update the date manually.

**Comment by blounsbury** [comment]
I commented on reddit. But I would also vote that the up/down arrow keys move the date +1 and -1 by week from the day rather than moving cursor. If I want to select a day 8 days ago using the keyboard I have to hit the left arrow key 8 times. If the up arrow key moved it -1 week, then I hit the up arrow and left arrow. So, 2 key strokes rather than 8.

**Comment by justbudget** [comment]
@blounsbury thanks for the suggestion! I tweaked the date picker and the change should be live on the website now.

**Comment by blounsbury** [comment]
Perfect! I run into this scenario when on vacation and then come back to enter transactions from a week ago. Much better! Thanks!
