### ISSUE TITLE
Ability to see running account balances on accounts

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#8]
Use case:

When viewing my transactions in my checking account, I want to be able to toggle a button to have a new column added that, next to the amount that shows the balance of the account after each transaction.

**Comment by bpaulien** [comment]
If/when scheduled/recurring transactions get implemented, it would also be nice to see the running balance into the future.  Use Case: I like to keep $x.xx buffer in checking.  If I have the ability to look forward at my expected balance in a couple weeks, including income and expenses that I know are coming.  it's easy to make a decision if I can transfer some over to savings account, or if my property taxes are coming due this month, I'll probably skip the transfer, in favor of keeping my buffer.

**Comment by Kidglove57** [comment]
100% for this

**Comment by justbudget** [comment]
Thanks for the extra comment. Do you both feel p2 is appropriate or should this be bumped up to p1?

**Comment by bpaulien** [comment]
Personally, I'd rather have it sooner than later, but I don't want to overwhelm you with p1 requests.  And since I'm currently running in parallel with Actual, I can see my running balance over there, so I'm not sure it's super urgent (to me).

**Comment by Kidglove57** [comment]
I will leave P1 or P2 to your discretion/workload! I certainly need some way to assess my forecast future balance. Two simple uses (1) making sure funds are ready to clear my Cashback credit card and (2) to make sure interest earned is maximised ie knowing when exactly to move funds back from savings to checking.

Like @bpaulien I am also still with Actual (and have been since 2019). However, I am concerned about Actual's future now that (a) it rests with just one maintainer who has lost impetus and regular commitment since going open source and (b) the complications of running on Fly or Docker should my wife have to take over the budget from me at some point in the future.

So Just Budget has come along at just the right time

**Comment by justbudget** [comment]
Sounds good! Thanks for the feedback, I'll bump it up to p1 for now, but probably won't get to it until the other P1s are done. Let me know if there are any others that you would consider "must have"s.

**Comment by Kidglove57** [comment]
"Let me know if there are any others that you would consider "must have"s."

I am sure that, as I get back into full testing, there may be other things that come to the fore. However, for now I have simply reviewed the P2 and P3s issue on Github to see if (in my view) any should be promoted to P1. In my particular set up. the following could prove vital:
1) International date formats - i look at the account ledger and have to think very hard about what the date shown means!
2) Issue #91 - transfers between on budget and "investment accounts. I do a lot of this. The only workaround I can think of for now would be to deal with each side separately. But of course transactions cannot be added as yet to Investments so I would need to do a commensurate balance adjustment instead. A thought - without the ability to add transactions to investments is not the transfer issue mute?

**Comment by justbudget** [comment]
Thanks for the feedback! Of course let me know if you encounter any other "must have"s as you go through and test. 

For 1) there is an issue for this already: https://github.com/justbudget/justbudget/issues/47 I'll bump it up to P1.
For 2), I'll bump up https://github.com/justbudget/justbudget/issues/91 to a P1, but you do raise an interesting question. I might need to tweak the investments view to allow transactions rather than just value updates. I also need to add support for "inline transfers" since you can't click and drag between on and off budget accounts.

**Comment by justbudget** [comment]
This is done as of https://www.reddit.com/r/justbudget/comments/x7kb1i/update_61_add_running_balances_to_account_view/?utm_source=share&utm_medium=web2x&context=3

Although currently there's no way to turn them _off_. We'll see if that's something people want in the future.
