### ISSUE TITLE
Moving money from "Available to budget"

### ISSUE THREAD

**Issue by bpaulien** [justbudget/justbudget#83]
I just got my paycheck, and noticed that if you drag from Available to budget to a category, that works the way you'd expect, but if you just click on Available to budget, it pulls up the "Move" screen, but the From category is not filled in.  It SHOULD be populated with "Available to budget"

I confirmed that it behaves the same way on the mobile app.

**Comment by justbudget** [comment]
I believe this is fixed now! Feel free to leave a comment if it's not, and I will re-open the issue.
