### ISSUE TITLE
Export transactions

### ISSUE THREAD

**Issue by jbmadsen2022** [justbudget/justbudget#84]
It would be nice to be able to export transactions into csv or similar format.

**Comment by justbudget** [comment]
I've implemented a first version of this. Hopefully the export includes the data you're looking for. Also please let me know if anything is off about the format of the CSV!

![giphy-2](https://user-images.githubusercontent.com/106850056/185009445-8f1c7cab-eefd-44f9-9aca-517421af5d93.gif)

**Comment by Kidglove57** [comment]
I have done a quick test and all appeared to be as expected! Thank you very much. 

By sorting by catergory or note and then restricting to a date range I can extract the key data I need for UK taxes. Charitable gifts as an example.

**Comment by justbudget** [comment]
Great, thanks for confirming! Glad it's working for you. Thanks to @jbmadsen2022 for filing this issue too, it's a nice feature to have while I work on landing things like filters and reports.

**Comment by Rick-Thomas** [comment]
A great addition to the app...   Very welcome!!!

I have a couple of request if they could be added:

1. Adding the Group to which the Category belongs...   In my case I have several Groups (Automobile, House, Personal, etc) that have an "Other" category...   Not having the Group in the export complicates the analysis of where that expense is from...   It also complicates the ability to have grand totals by the different Groups...
2. Adding the "Available to Budget" in the Category field...   Not sure why, when it's an income, which, when imputed, it does so with an "Available to Budget" category, is blank in the exported file...

The users of a different character set than the standard US character set, will have a character translation problem...  In my case I use Spanish Latin America which includes vowels that have accents or umlauts (I think that is what it's called  -two dots on the u)  and those are translated into funny combination of 3 characters!!!   I will have to see how to solve that on the exported file... 

I'm adding this after posting...   The character set problem I have managed to resolve, importing the .csv file with the Get & Transform facility in Excel and selecting a different char set...   

Thanks very much for this Export facility...   It is one of my musts to move over to JB!!!

**Comment by justbudget** [comment]
Thanks for the feedback! Glad you figured out the character set issue. I think for now I'll leave the characters as is - I'm using the default CSV export settings which hopefully will be the most universal.

> Adding the Group to which the Category belongs...

Done, I added a column for "Group" right before the "Category" column.

> Adding the "Available to Budget" in the Category field... 

Done, although apologies if it shows up in some places where it _shouldn't_. I don't think it's perfect yet.

Changes should be live on the web now!

**Comment by Rick-Thomas** [comment]
Fantastic!!!   Works perfect, and the "Available to budget" shows up in the Category field, so no apologies necessary!!!   ;-)

Thanks for the great response time!!!  Crossing my fingers for split transactions, which should include transfers, and some other ones on your P1 list!!!   Very enthusiastic and appreciative the way one sees the app moving forward at a nice speed...

**Comment by justbudget** [comment]
Glad it worked for you! 

Yep, Split Transactions is a p1, so it's a top priority issue. And thanks for the reminder about split transactions including transfers, I marked https://github.com/justbudget/justbudget/issues/96 as a p1 again since that would be necessary for split transactions with transfers.

> Very enthusiastic and appreciative the way one sees the app moving forward at a nice speed...

Thank you for the encouragement!
