### ISSUE TITLE
static left arrow location when switching between months

### ISSUE THREAD

**Issue by blounsbury** [justbudget/justbudget#89]
When switching between months it would be nice if the left arrow remained in a static location rather than adjusting to the length of the month name, which requires mouse movements to click on where the left arrow is moving. Hopefully that makes sense.

**Comment by bpaulien** [comment]
Yes, looks like September is *slightly* longer than November or December.  Maybe keep that length, and put the left arrow there.  then perhaps center the name of the month between the arrows?  Or keep it left aligned, I don't know.  Whatever looks better.  I'm not a UI guy, I just agree that you don't want to be moving your cursor to click multiple times on the arrow.

**Comment by justbudget** [comment]
This has definitely bothered me too, thanks for filing an issue. When you want to _click_ _click_ _click_ backwards it's annoying that you can't easily flip through the months. I think ideally the month text should take up the same width regardless of the length of the text.
