### ISSUE TITLE
Should save list of "recipients" 

### ISSUE THREAD

**Issue by justbudget** [justbudget/justbudget#9]
Use case:

As I'm entering my June rent, I want to type "Landl..." into recipient and be shown a list of past recipients. I want to tap on "Landlord" and then have the category automatically populate with "Rent", since the last payment I made to "Landlord" was from the "Rent" category.

**Comment by bpaulien** [comment]
Just a comment on this.  I don't want to tap on it.  I want to hit tab, and continue typing in the rest of the transaction.  Tab or Enter should be able to substitute for tapping on the selected entry.  If it's not selected, arrow keys should be able to move to it, then tab/enter.  The point is to keep your hands on the keyboard as much as possible.  Going between data entry and mouse movement is not efficient.

**Comment by justbudget** [comment]
This is complete as of version `1.2.2`.
![giphy](https://user-images.githubusercontent.com/106850056/183673290-0f9845a5-183a-450b-9cd4-64386a174ca0.gif)

This includes @bpaulien's suggestion of allowing for "tab" to select.

**Comment by blounsbury** [comment]
Noticed one item.

1. Editing a transactions and changing the recipient doesn't save a new recipient to the list of recipients.

**Comment by justbudget** [comment]
@blounsbury, good catch, fixed! Should be live on the web now, will be included in the next version of the mobile apps.
