### ISSUE TITLE
Edit transaction - date picker does not change date

### ISSUE THREAD

**Issue by blounsbury** [justbudget/justbudget#95]
I was trying to edit the date for an existing transaction. I click on the calendar icon which brings up the date picker, select a different date, hit Save, and the date does not change. Same thing happens with new transactions using the + button to add an expense or income. The date picker does not do anything.

Also, I'd love to see the date picker used for inline transactions also used with the + button to add transactions.

**Comment by justbudget** [comment]
Thanks for flagging this! You're totally right it wasn't working properly.

> Also, I'd love to see the date picker used for inline transactions also used with the + button to add transactions.

Thanks for the suggestion, I went ahead and did this, I removed the old date picker entirely! It seems cleaner now, although it might be that the new date picker is too tiny for mobile. We'll see how it goes!

For reference, here's what the date picker looks like now that I've made the change <img width="278" alt="Screen Shot 2022-08-20 at 12 22 13 AM" src="https://user-images.githubusercontent.com/106850056/185718739-8c6a9389-5f69-46f2-9371-3cf13b895ac7.png">
